const refs = {
  questionsList: document.querySelector('.js-landing-questions-list'),
  consultationForm: document.querySelector('.js-landing-consultation-form'),
  consultationFormSubmitBtn: document.querySelector('.js-landing-consultation-form-submit-btn'),
  consultationSuccessMsg: document.querySelector('.js-landing-consultation-success-form-submit-msg'),
  consultationSuccessMsgCloseBtn: document.querySelector('.js-landing-consultation-success-form-submit-msg-close-btn'),
  footerForm: document.querySelector('.js-landing-footer-form'),
  footerFormSubmitBtn: document.querySelector('.js-landing-footer-form-submit-btn'),
  trialLessonBtns: document.querySelectorAll('.js-trial-lesson-btn'),
  trialLessonModalWin: document.querySelector('.js-trial-lesson-modal-win'),
  trialLessonModalWinCloseBtn: document.querySelector('.js-trial-lesson-modal-win-close-btn'),
  showTrialLessonsListToggleBtn: document.querySelector('.js-show-trial-lessons-list-toggle-btn'),
  trialLessonsList: document.querySelector('.js-trial-lessons-list'),
  trialLessonForm: document.querySelector('.js-trial-lesson-form'),
  trialLessonFormSubmitBtn: document.querySelector('.js-landing-trial-lesson-form-submit-btn'),
  trialLessonSuccessMsg: document.querySelector('.js-landing-trial-lesson-success-form-submit-msg'),
  trialLessonSuccessMsgCloseBtn: document.querySelector('.js-landing-trial-lesson-success-form-submit-msg-close-btn'),
  regOnCourseBtns: document.querySelectorAll('.js-reg-on-course-btn'),
  regOnCourseModalWin: document.querySelector('.js-reg-on-course-modal-win'),
  regOnCourseModalWinCloseBtn: document.querySelector('.js-reg-on-course-modal-win-close-btn'),
  showRegOnCourseListToggleBtn: document.querySelector('.js-show-reg-on-course-list-toggle-btn'),
  regOnCourseList: document.querySelector('.js-reg-on-course-list'),
  regOnCourseFormSubmitBtn: document.querySelector('.js-landing-reg-on-course-form-submit-btn'),
  regOnCourseForm: document.querySelector('.js-reg-on-course-form'),
  regOnCourseSuccessMsg: document.querySelector('.js-landing-reg-on-course-success-form-submit-msg'),
  regOnCourseSuccessMsgCloseBtn: document.querySelector('.js-landing-reg-on-course-success-form-submit-msg-close-btn'),
  landingModalWinBackdrop: document.querySelectorAll('.js-landing-backdrop'),
};

export default refs;
