const refs = {
  questionsList: document.querySelector('.js-landing-questions-list'),
  trialLessonBtns: document.querySelectorAll('.js-trial-lesson-btn'),
  trialLessonModalWin: document.querySelector('.js-trial-lesson-modal-win'),
  trialLessonModalWinCloseBtn: document.querySelector('.js-trial-lesson-modal-win-close-btn'),
  showTrialLessonsListToggleBtn: document.querySelectorAll('.js-show-trial-lessons-list-toggle-btn'),
  trialLessonsList: document.querySelector('.js-trial-lessons-list'),
  regOnCourseBtns: document.querySelectorAll('.js-reg-on-course-btn'),
  regOnCourseModalWin: document.querySelector('.js-reg-on-course-modal-win'),
  regOnCourseModalWinCloseBtn: document.querySelector('.js-reg-on-course-modal-win-close-btn'),
  landingModalWinBackdrop: document.querySelectorAll('.js-landing-backdrop'),
  successMsg: document.querySelector('.js-landing-success-form-submit-msg-modal-win'),
  showTrialLessonsListToggleBtnTitle: document.querySelector('.js-landing-trial-lesson-form-list-btn-title'),
  showRegOnCourseListToggleBtnTitle: document.querySelector('.js-landing-reg-on-course-form-list-btn-title'),
  coursesList: document.querySelector('.js-landing-courses-list'),
  aboutLessonModalWin: document.querySelector('.js-about-lesson-modal-win'),
  aboutLessonModalWinTitle: document.querySelector('.js-landing-about-lesson-modal-win-title'),
  aboutLessonCloseBtn: document.querySelector('.js-about-lesson-modal-win-close-btn'),
  aboutLessonRegBtn: document.querySelector('.js-landing-about-lesson-modal-win-reg-btn'),
  reviewsList: document.querySelector('.js-landing-reviews-list'),
  mobileMenuBtn: document.querySelector('.js-header-landing-hamburger-btn'),
  mobileMenu: document.querySelector('.js-header-landing-mobile-menu'),
  mobileMenuCloseBtn: document.querySelector('.js-header-landing-close-mobile-menu'),
};

export default refs;
